fruit = []
f1 = input("Enter Name of Fruit")
fruit.append(f1)
f2 = input("Enter Name of Fruit")
fruit.append(f2)
f3 = input("Enter Name of Fruit")
fruit.append(f3)
f4 = input("Enter Name of Fruit")
fruit.append(f4)
f5 = input("Enter Name of Fruit")
fruit.append(f5)
f6 = input("Enter Name of Fruit")
fruit.append(f6)
print(fruit)

