print("Enter your name")
name = input()
print(f"Good after noon {name}")
print(f"Hello {name}")
print(f"Nice to see you {name}")
print(f"Welcome to our website {name}")
print(f"Now {name} Understood Format string closely ")