 = int(input("Enter the number"))
# set.add(n)
# n = int(input("Enter the number"))
# set.add(n)
# n = int(input("Enter the number"))
# set.add(n)
# n = int(input("Enter the number"))
# set.add(n)
# n = int(input("Enter the number"))
# set.add(n)
# n = int(input("Enter the number"))
# set.add(n)
# n = int(input("Enter the number"))
# set.add(n)